#fullnameOverride: ""

replicaCount: 1

image:
  repository: mortus1111/python-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: my-domain.local
      paths:
      - path: /
        pathType: ImplementationSpecific
